### ISSUE TITLE
(Not a script error!) Python Package Availability

### ISSUE THREAD

**Issue by ceruleane** [soundray/maper#1]
Dear Authors,

Hello. I was wondering if you provide a python package for MAPER as I'm trying to apply this software directly into my python script. Would you mind if you could let me know if you have any plans regarding such, and even better, if you already have such package openly available?

I'm very sorry for asking through this issue section..

**Comment by soundray** [comment]
Thank you for the suggestion. Would it be an option for you to call MAPER scripts via os.system()?
