### ISSUE TITLE
RegistrationEnergy::Value: Value of term Image dissimilarity is NaN!

### ISSUE THREAD

**Issue by Shavi123** [soundray/maper#2]
Dear Authors,

I am trying to use MAPER to generate volumetric data for one T1w Skullstripped MRI scan. I followed the steps mentioned in the repo for installation as well as for setting up HM atlas directory. After running the commands i am getting below error -
RegistrationEnergy::Value: Value of term Image dissimilarity is NaN!

I got the same error in test run as well.

I have no idea how to resolve this, did i made any mistake in installing the software?
Kindly guide me.
![Screenshot from 2022-01-20 21-37-42](https://user-images.githubusercontent.com/7808469/150426212-2f31b71e-5c82-4a89-8794-7a1b52246dfd.png)

**Comment by soundray** [comment]
Thank you for your report. I fixed a bug in `launchlist-gen`. This fix may resolve your problem -- please pull the new version and let me know how it goes. Be sure to delete the existing output-dir for the new run.
